# Básico e Fundamentos

### Passo 1 - Leitura do arquivo CSV

In [2]:
import pandas as pd 

# Carregando os dados do arquivo CSV para um DataFrame
df = pd.read_csv('~/work-environment/study-files/vendas.csv')

In [3]:
# Exibe o objeto criado para confirmar a leitura
display(df)

,id_venda,data,cliente,categoria,valor_venda,quantidade,regiao
0,1001,2024-01-15,Ana Silva,Eletrônicos,1200.5,1,Sudeste
1,1002,2024-01-16,Bruno Souza,Móveis,850.0,2,Sul
2,1003,2024-01-16,Carla Dias,Eletrônicos,3500.0,1,Sudeste
3,1004,2024-01-17,Diego Alves,Vestuário,150.0,3,Nordeste
4,1005,2024-01-18,Elena Lima,Móveis,1200.0,1,Centro-Oeste
5,1006,2024-01-18,Fabio Costa,Eletrônicos,250.0,2,Sudeste
6,1007,2024-01-19,Gisele Rocha,Vestuário,450.0,4,Sul
7,1008,2024-01-20,Heitor Ramos,Eletrônicos,5000.0,1,Norte

### Passo 2 - Entendendo a Estrutura (Tamanhos e Tipos)

In [4]:
# 1. Quantas linhas e colunas temos?
display("Formato da base(linhas, colunas):", df.shape)

'Formato da base(linhas, colunas):'

(8, 7)

In [5]:
# 2. Resumo com os tipos de dados e memória
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_venda     8 non-null      int64
 1   data         8 non-null      str
 2   cliente      8 non-null      str
 3   categoria    8 non-null      str
 4   valor_venda  8 non-null      float64
 5   quantidade   8 non-null      int64
 6   regiao       8 non-null      str
dtypes: float64(1), int64(2), str(4)
memory usage: 880.0 bytes

### Passo 3 - Inspecionando o início e fim do DataFrame

In [6]:
# 1. Visualiza as 3 primeiras linhas
display(df.head(3))

,id_venda,data,cliente,categoria,valor_venda,quantidade,regiao
0,1001,2024-01-15,Ana Silva,Eletrônicos,1200.5,1,Sudeste
1,1002,2024-01-16,Bruno Souza,Móveis,850.0,2,Sul
2,1003,2024-01-16,Carla Dias,Eletrônicos,3500.0,1,Sudeste

In [7]:
# 2. Visualiza as 3 últimas linhas
display(df.tail(3))

,id_venda,data,cliente,categoria,valor_venda,quantidade,regiao
5,1006,2024-01-18,Fabio Costa,Eletrônicos,250.0,2,Sudeste
6,1007,2024-01-19,Gisele Rocha,Vestuário,450.0,4,Sul
7,1008,2024-01-20,Heitor Ramos,Eletrônicos,5000.0,1,Norte

Serve pra validar rapidamente os nomes das colunas e alinhamento inicial dos dados após a leitura. A parte final também é importante para identificar se o arquivo possui "lixo" no final.

### Passo 4 - Resumo Estatístico Numérico

In [8]:
# Gera estatísticas descritivas para todas as colunas numéricas
display(df.describe())

         id_venda  valor_venda  quantidade
count     8.00000     8.000000    8.000000
mean   1004.50000  1575.062500    1.875000
std       2.44949  1744.158627    1.125992
min    1001.00000   150.000000    1.000000
25%    1002.75000   400.000000    1.000000
50%    1004.50000  1025.000000    1.500000
75%    1006.25000  1775.375000    2.250000
max    1008.00000  5000.000000    4.000000

O médoto *.describe()* é o principal "raio-x" numérico no início de uma **Análise Exploratória de Dados (EDA).**

### Passo 5 - Análise de contagem e frequência de categorias

O método describe foca apenas em colunas numéricas. Para análisar **colunas de texto/categorias** como categorias ou região, usamos a função *value_counts()* em uma Series

In [9]:
# Contagem de vendas por categoria de produtos
display(df['categoria'].value_counts())

categoria
Eletrônicos    4
Móveis         2
Vestuário      2
Name: count, dtype: int64

In [10]:
# Contagem de vendas por região
display(df['regiao'].value_counts())

regiao
Sudeste         3
Sul             2
Nordeste        1
Centro-Oeste    1
Norte           1
Name: count, dtype: int64

Permite responder instantaneamente perguntas de negócios sem precisar de agrupamentos complexos, tais como: "*Qual é a categoria mais vendida?*" ou "*Qual região com maior volume de transações?*"

### Passo 6 - Ordenação de Dados

In [11]:
# Ordena o DataFrame pelo valor da venda do maior para o menos, ou vice versa
df_ordenado = df.sort_values(by='valor_venda', ascending=False)

display(df_ordenado)

,id_venda,data,cliente,categoria,valor_venda,quantidade,regiao
7,1008,2024-01-20,Heitor Ramos,Eletrônicos,5000.0,1,Norte
2,1003,2024-01-16,Carla Dias,Eletrônicos,3500.0,1,Sudeste
0,1001,2024-01-15,Ana Silva,Eletrônicos,1200.5,1,Sudeste
4,1005,2024-01-18,Elena Lima,Móveis,1200.0,1,Centro-Oeste
1,1002,2024-01-16,Bruno Souza,Móveis,850.0,2,Sul
6,1007,2024-01-19,Gisele Rocha,Vestuário,450.0,4,Sul
5,1006,2024-01-18,Fabio Costa,Eletrônicos,250.0,2,Sudeste
3,1004,2024-01-17,Diego Alves,Vestuário,150.0,3,Nordeste

### Passo 7 - Seleção Condicional / Indexação Booleana

In [12]:
# 1. Cria uma máscara booleana (retorna True ou False para cada linha)
mascara = df['valor_venda'] > 1000

# 2. Aplica a máscara no DataFrame para filtrar apenas as linhas True
vendas_altas = df[mascara]

display(vendas_altas)

,id_venda,data,cliente,categoria,valor_venda,quantidade,regiao
0,1001,2024-01-15,Ana Silva,Eletrônicos,1200.5,1,Sudeste
2,1003,2024-01-16,Carla Dias,Eletrônicos,3500.0,1,Sudeste
4,1005,2024-01-18,Elena Lima,Móveis,1200.0,1,Centro-Oeste
7,1008,2024-01-20,Heitor Ramos,Eletrônicos,5000.0,1,Norte

Essa é uma forma nativa do Pandas para filtrar dados. Evita uso de laços *for* do python, garantindo máxima velocidade de processamento, mesmo em bases com milhões de linhas

### Passo 8 - Filtragem Condicional com Múltiplas Condições

In [13]:
# Múltiplas condições: categoria 'Eletronicos' e Região 'Sudeste'
mascara_composta = (df['categoria'] == 'Eletrônicos') & (df['regiao'] == 'Sudeste')

vendas_eletronicas_sudeste = df[mascara_composta]

display(vendas_eletronicas_sudeste)

,id_venda,data,cliente,categoria,valor_venda,quantidade,regiao
0,1001,2024-01-15,Ana Silva,Eletrônicos,1200.5,1,Sudeste
2,1003,2024-01-16,Carla Dias,Eletrônicos,3500.0,1,Sudeste
5,1006,2024-01-18,Fabio Costa,Eletrônicos,250.0,2,Sudeste

- **Operadores Bitwise(& para E, | para ou):** No python padrão usamos *and* e *or*, mas no pandas **devemos obrigatóriamente usar & e |**. Isso ocorre por que precisamos comparar cada elemento dos arrays veotorizados linha a linha

- **Uso obrigatório do Parênteses:** Em python, o operador & tem prioridade matemática sobre os operadores de comparação (==, >, <). Se não colocar parênteses em cada condição individual *(condicao1) & (condicao2)*, o python gera um erro de sintaxe ou avalia a expressão incorretamente.

### Passo 9 - Indexação Profissional com *loc* e *iloc*

- .loc (Baseado em Rótulos / Nomes): Usa os nomes das colunas e os índices das linhas.

- .iloc (Baseado em Posição Númerica): Usa números de posição inteiros 0, 1, 2, ... tal como python nativo

In [14]:
# 1. Usando .loc: Seleciona linhas de índice 0 a 3, trazendo apenas as colunas 'cliente' e 'valor_venda'
subconjunto_loc = df.loc[0:3, ['cliente', 'valor_venda']]

display(subconjunto_loc)

       cliente  valor_venda
0    Ana Silva       1200.5
1  Bruno Souza        850.0
2   Carla Dias       3500.0
3  Diego Alves        150.0

In [15]:
# 2. Usando .iloc: Seleciona as primeiras 3 linhas (índices 0 a 2) e as primeiras 2 colunas (índices 0 e 1)
subconjunto_iloc = df.iloc[0:3, 0:2]

display(subconjunto_iloc)

   id_venda        data
0      1001  2024-01-15
1      1002  2024-01-16
2      1003  2024-01-16

### Passo 10 - Criação e Alteração de Colunas Derivadas

In [18]:
# Cria a coluna 'faturamento' multiplicando valor_venda por quantidade
df['faturamento'] = df['valor_venda'] * df['quantidade']

display(df)

,id_venda,data,cliente,categoria,valor_venda,quantidade,regiao,faturamento
0,1001,2024-01-15,Ana Silva,Eletrônicos,1200.5,1,Sudeste,1200.5
1,1002,2024-01-16,Bruno Souza,Móveis,850.0,2,Sul,1700.0
2,1003,2024-01-16,Carla Dias,Eletrônicos,3500.0,1,Sudeste,3500.0
3,1004,2024-01-17,Diego Alves,Vestuário,150.0,3,Nordeste,450.0
4,1005,2024-01-18,Elena Lima,Móveis,1200.0,1,Centro-Oeste,1200.0
5,1006,2024-01-18,Fabio Costa,Eletrônicos,250.0,2,Sudeste,500.0
6,1007,2024-01-19,Gisele Rocha,Vestuário,450.0,4,Sul,1800.0
7,1008,2024-01-20,Heitor Ramos,Eletrônicos,5000.0,1,Norte,5000.0

### Passo 11 - Exportação de Dados Tratados

In [19]:
# Salva o DataFrame modificado em um novo ficheiro CSV
df.to_csv('~/work-environment/study-files/vendas_limpo.csv', index=False)

- **to_csv('caminho/ficheiro.csv'):** Exporta a estrutura bidimensional do DataFrame para um ficheiro de texto separado por vírgulas.

- **index=False (crucial):** Por padrão, o Pandas tenta gravar a coluna de índices numéricos (0, 1, 2...) no ficheiro csv. Definir *index=False* evita que seja criada uma coluna sem nome inútil sempre que reabrir o ficheiro no futuro.

## O que aprendi

Com esse conjunto de ferramentas no Pandas já consigo criar pequenas análises e entender como é o conjunto de dados. São um conjunto de ferramentas necessário para iniciar, e que dão uma base muito boa par qualquer avaliação de dataset.